### PR TITLE
Switch Microsoft 365 (formerly Office 365) to OAuth2.

### PR DESCRIPTION
**Pull request by mkmelin**
See https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-september-2021-update/ba-p/2772210

### CODE REVIEW

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
Side note: K-9 Mail uses the scopes `https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access`. Those work for both business and personal (outlook.com, hotmail.com etc) accounts.

**Comment by Sancus** [comment]
The current patch on https://phabricator.services.mozilla.com/D158588 also uses outlook.office.com so we should probably change that.

And once the patch is on ESR, we should probably change https://github.com/thundernest/autoconfig/blob/master/ispdb/hotmail.com as well.

**Comment by mkmelin** [comment]
It still needs merging to the prod branch to show up for users - https://autoconfig.thunderbird.net/v1.1/office365.com
Or does that happen automatically?

**Comment by Sancus** [comment]
> It still needs merging to the prod branch to show up for users - https://autoconfig.thunderbird.net/v1.1/office365.com Or does that happen automatically?

Did that, yeah. Looks good to me now.

**Comment by benbucksch** [comment]
Re scopes, https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth also says to use `https://outlook.office.com/IMAP.AccessAsUser.All` etc. as scopes.

**Pull request merged**
