### PR TITLE
Remove Posteo

### PR DESCRIPTION
**Pull request by phifty**

### CODE REVIEW

**Comment by benbucksch** [comment]
There's no reason to do that.

**Comment by phifty** [comment]
Posteo asks me to commit this pull-request. If additional verification is needed, please contact Posteo by mail to support@posteo.de. I excuse the inconvenience.

**Comment by cketti** [comment]
Did they provide a reason? 

It looks like they host their own config under https://autoconfig.posteo.de/mail/config-v1.1.xml. However, the same is not true for all the other domains listed in the config (posteo.at, posteo.ch, etc.). Removing the ISPDB config will mean automatic setup in Thunderbird (and probably other clients) will stop working for email addresses using these domains.

**Comment by benbucksch** [comment]
What cketti said.

Also, even if posteo hosts their own config, we would like to keep the config here for backup, statistics etc, for ISPs. The self-hosted config will override (be preferred over) the config in the ISPDB, so it doesn't do any harm.

**Comment by benbucksch** [comment]
https://posteo.de/hilfe/welche-domains-stehen-fuer-alias-adressen-zur-verfuegung

**Pull request closed without merging**
