### PR TITLE
Update settings for Charter

### PR DESCRIPTION
**Pull request by cketti**
- Removes entries with `<socketType>plain</socketType>`.
- Adds POP3 settings.
- Adds the domains `spectrum.net` and `bresnan.net` that use the same mail server settings.

https://www.spectrum.net/support/internet/mobile-email-setup

### CODE REVIEW

**Review by benbucksch — CHANGES_REQUESTED** [review]
Can you please leave charter.com.xml as filename ? Thanks

**Comment by cketti** [comment]
https://www.charter.com doesn't seem to be functional anymore. And `charter.com` doesn't seem to be an email domain usable by customers (that's why I removed the `<domain>` entry). What would be the upside of keeping the original name?

**Comment by Sancus** [comment]
What's the benefit of keeping the filename if the domain is defunct on the web and not being used for email at all?

**Comment by benbucksch** [comment]
> What's the benefit of keeping the filename if the domain is defunct on the web and not being used for email at all?

git log history

**Comment by Sancus** [comment]
> > What's the benefit of keeping the filename if the domain is defunct on the web and not being used for email at all?
> 
> git log history (and - less importantly - being able to read the diff here)

The diff should be a [separate commit from the rename](https://github.com/thundernest/autoconfig/pull/68/commits/79e7dbed2e3a06a95f5d7a104f1688a6cad3e62c), as it is now, so you can read the diff. 

I don't understand the log issue. Renames are just a normal part of the history, they don't interfere with anything else. If [you look at the fil](https://github.com/thundernest/autoconfig/blame/update_charter/ispdb/charter.net.xml)e you can see the blame continues to work just fine even for changes prior to the rename.

**Comment by cketti** [comment]
I rewrote the branch to separate the content change from the file rename yesterday. Previously it was just one commit and enough content changed for Git to not consider it the same file. Now Git clients should be able to track the whole history of the file.

**Pull request merged**
