### PR TITLE
Remove exchange option - following bug 1592258 and related discussion.

### PR DESCRIPTION
**Pull request by mkmelin**
Remove exchange account types, mitigating bug [1592258](https://bugzilla.mozilla.org/show_bug.cgi?id=1592258) across all branches.

### CODE REVIEW

**Comment by benbucksch** [comment]
This is going directly against the TB Council decision.

**Comment by mkmelin** [comment]
This is the exact core of the council decision: remove exchange, and do it now before any more users are affected. I quote the decision:  

**Remove exchange option for free accounts (Hotmail/Outlook). Remove exchange option for Office365 as well - “back to original terms”.**

**Comment by benbucksch** [comment]
ISPDB policy is and always has been to only show configs as default that are working for **all** users, not just some of them. See for example my comment on [Yahoo](https://github.com/thundernest/autoconfig/pull/2#issuecomment-406262492), and many others. In this case, it's already not the default, just an alternative, and you want to completely remove the option for all these users.

>  Remove exchange option for free accounts (Hotmail/Outlook). Remove exchange option for Office365 as well - “back to original terms”.

For the record, I checked the text of the official TB Council decision as communicated to me (Philipp Kewisch on behalf of TB Council, 2019-11-20 00:07 CET), and this is sentence is not part of it. Rather, the sentence: "Exchange should only be advertised to the user if the other supported protocols such as IMAP are not available".

Your proposal here is in direct contradiction of that, and would break it. You're removing known working configs and advertise configs that will not work for many users.

**Comment by jorgk3** [comment]
Huh, does this even apply? Exchange was removed from the hotmail file in
https://github.com/thundernest/autoconfig/commit/5d19835f00870ead203df15730cdff777908fed2

**Comment by Sancus** [comment]
> 
> 
> Huh, does this even apply? Exchange was removed from the hotmail file in
> [5d19835](https://github.com/thundernest/autoconfig/commit/5d19835f00870ead203df15730cdff777908fed2)

Yes, this branch is based on a master 6 commits old, but it would still merge without conflict because the final state of the files is the same.

**Comment by benbucksch** [comment]
FYI, the TB Council is discussing this. I am respectfully awaiting their official response before anything moves here.

**Comment by mkmelin** [comment]
Thunderbird was changed to do more checks for when to offer exchange in office365 - it now selects it only when other options would not work.
I've moved the exchange option last again, https://github.com/thundernest/autoconfig/commit/a75bd2409e9f2d9f055fc855205c7898d2e4f2d0

**Pull request closed without merging**
